name: flutter_wechat_qrcode
description: "QRScan by WeChat project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.weatherfish.flutter_wechat_qrcode
        pluginClass: FlutterWechatQrcodePlugin
      ios:
        pluginClass: FlutterWechatQrcodePlugin

