name: flutter_wechat_qrcode
description: "QRScan by WeChat project."
version: 0.0.3
repository: https://github.com/weatherfish/flutter_wechat_qrcode
homepage:

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.weatherfish.flutter_wechat_qrcode
        pluginClass: FlutterWechatQrcodePlugin
      ios:
        pluginClass: FlutterWechatQrcodePlugin

